on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/main.yaml

jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -Ahlt .git
      - run: ls -Ahlt .git/objects
      - run: ls -Ahlt .git/objects/of
